### ISSUE TITLE
Model filler objects

### ISSUE THREAD

**Issue by DawnEggleton** [DawnEggleton/TheObservationTrail#13]
- [x] Tall cube for tree (2.5x the size of reference man)
- [x] Plane for ground
- [x] Medium cube for animal (4ft)
- [x] Small cube for object 

Find and import an open source human model to compare height. There is also a height chart in the google docs that you can load in as a reference image.
Export models and OBJ types and add to repository

**Comment by KaliaH25** [comment]
Filler objects have been added to new VRtestEnviro branch.
