### ISSUE TITLE
Code guidebook template

### ISSUE THREAD

**Issue by DawnEggleton** [DawnEggleton/TheObservationTrail#15]
- [x] Adapt from previous work
- [x] Adjust CSS
- [x] Make mobile-friendly
- [x] Comment code for easy editing by other group members

**Comment by yousefAR88** [comment]
![vectorized](https://user-images.githubusercontent.com/46602486/52246052-3af5fc80-28b2-11e9-813a-87f3e693be4e.png)

**Comment by DawnEggleton** [comment]
Note to self for blog: 6 hours so far on this
