### ISSUE TITLE
Model and texture rock and mossy rock

### ISSUE THREAD

**Issue by DawnEggleton** [DawnEggleton/TheObservationTrail#19]

**Comment by DawnEggleton** [comment]
a large, decorative rock for the environment. preferably, make two sizes - medium and large - and then two textures for each - one to be not-mossy and one to be mossy, so we can assign them variably for a nicer, more natural looking setting in-game

**Comment by KaliaH25** [comment]
If you want some randomly generated rocks to use as a jumping off point, run the following python script in maya 
`
#stocastic generation of a rock
import random
import maya.cmds as cmds


def generateNumber(_min,_max):

    return(random.uniform(_min,_max))
    #returns a random float between min and max


def vertexJitter(_object,_min,_max):

    #randomly displaces vertices of rock
    vertex_count = cmds.polyEvaluate(_object[0],vertex=True)
    
    
    for v in range(vertex_count):
        cmds.select(_object[0] + ".vtx[" + str(v) + "]")
        cmds.move(generateNumber(_min,_max),generateNumber(_min,_max),generateNumber(_min,_max),xyz=True,relative=True)
        
    


def generateRock():
    
    w=generateNumber(0.5,1.5)
    h=generateNumber(0.4,1.5)
    d=generateNumber(1.0,1.6)
    
    rock = cmds.polyCube(width=w,height=h,depth=d)
    #save polyCube as variable
    
    cmds.move(0,-1*(h/2),0,rock[0]+".scalePivot",rock[0]+".rotatePivot",absolute=True)
    #moves pivot point to bottom center of poly 
	
    cmds.select(rock[0] + ".f[3]")
    #selects bottom face of cube           
    cmds.delete()
    #deletes selected face
    
    cmds.select(rock[0])
    cmds.polyPoke()
    #pokes cube to triangulate
    cmds.polySmooth(divisions=3)
    #smoothes cube
    
    vertexJitter(rock,-0.05,0.05)
    #displace verticies
    
    cmds.select(rock[0])
    cmds.polyReduce(percentage=generateNumber(94,99))
    #reduces the faces by a randomly generated percentage
    
    cmds.polySoftEdge(angle=0)
    #ensures the angle is shaded hard
    
    return rock

   for i in range(1):

       rock = generateRock()
       cmds.select(rock[0])
       #cmds.move(generateNumber(-5,5),0,generateNumber(-5,5),xyz=True,relative=True)
       #uncomment above line and comment out line below if you are making more then one rock 
       cmds.move(0,0,0,xyz=True,relative=True)

`

**Comment by DawnEggleton** [comment]
material connection issue; yousef working on
