### ISSUE TITLE
Model and texture rock action item

### ISSUE THREAD

**Issue by DawnEggleton** [DawnEggleton/TheObservationTrail#21]

**Comment by DawnEggleton** [comment]
A small, hand-sized rock.

**Comment by KaliaH25** [comment]
might want to reference the Oculus hand models: https://developer.oculus.com/downloads/package/oculus-hand-models/ 

remember to compare the size to our established meter man/height chart

**Comment by KaliaH25** [comment]
Models have been re-scaled. Compare and modify final model before pushing

**Comment by DawnEggleton** [comment]
Needs to be put in the models folder of the deciEnviro branch.
