### ISSUE TITLE
Model and texture racoon

### ISSUE THREAD

**Issue by DawnEggleton** [DawnEggleton/TheObservationTrail#28]

**Comment by KaliaH25** [comment]
Done, added to deciEnviro branch
![image](https://user-images.githubusercontent.com/24461999/53827130-65d27f80-3f48-11e9-97a2-8a1f374475cb.png)
![image](https://user-images.githubusercontent.com/24461999/53827139-6e2aba80-3f48-11e9-9d1e-387579ce8d73.png)
