### ISSUE TITLE
Key Features/Scope

### ISSUE THREAD

**Issue by DawnEggleton** [DawnEggleton/TheObservationTrail#4]

**Comment by DawnEggleton** [comment]
Did some grammar editing, but otherwise looks good - will let the others look it over too!

**Comment by KaliaH25** [comment]
looks good. Maybe add a line in the movement or interaction section that mentions the ability to track elevation of the headset (if we want the hiker to duck to avoid something flying) 
Also mention that we want to keep the animal and environmental models to a 1:1 scale. I don't think that is something to necessarily be assumed by the reader and size is a part of our sorting method into our guide book
