### ISSUE TITLE
Wireframes/Storyboards

### ISSUE THREAD

**Issue by DawnEggleton** [DawnEggleton/TheObservationTrail#8]

**Comment by KaliaH25** [comment]
Guide Book wire frames (mobile and desktop) are done and ready for PR

**Comment by DawnEggleton** [comment]
- [x] Dawn Reviewed
- [ ] Omar Reviewed
- [ ] Yousef Reviewed

**Comment by KaliaH25** [comment]
Added guidebook wireframe with popup event

**Comment by KaliaH25** [comment]
Finished the VR/Hiker wireframes for HMD and desktop. Compiled all the wireframes into a single PDF and uploaded the PSDs. 
Let me know if there's anything I left out. Will be doing a simple write up for the wireframes in our doc
-EDIT-
Managed to leave a screen out of the pdf, re-uploaded the file to shared drive
